#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "post-commit".



printf "Running the post-commit hook...\n"


GIT_DIR_="$(git rev-parse --git-dir)"
updateVersionScript=$GIT_DIR_/../.githooks/__post-git-hook.sh


# Run the version update script.
if sh $updateVersionScript
then
    printf "The post-commit hook successfully ran '$updateVersionScript'.\n"
else
    printf "Could not run the update program '$updateVersionScript' properly!\n"
    exit 1
fi


# Exits the program using a successful exit status code.
exit 0

