git submodule add -- https://github.com/evandrocoan/SublimeActiveViewJumpBack          "Packages/Active View Jump Back"
git submodule add -- https://github.com/evandrocoan/SublimeANSI                        "Packages/ANSIescape"
git submodule add -- https://github.com/evandrocoan/AddFolderToProject-SublimePlugin   "Packages/Add Folder To Project"
git submodule add -- https://github.com/evandrocoan/Sublime-Text-Advanced-CSV          "Packages/Advanced CSV"
git submodule add -- https://github.com/evandrocoan/Sublime-AdvancedNewFile            "Packages/AdvancedNewFile"
git submodule add -- https://github.com/evandrocoan/AlignTab                           "Packages/AlignTab"
git submodule add -- https://github.com/evandrocoan/SublimeAllAutocomplete             "Packages/All Autocomplete"
git submodule add -- https://github.com/evandrocoan/SublimeAMXX_Editor                 "Packages/amxmodx"
git submodule add -- https://github.com/evandrocoan/SublimeAmxxPawn                    "Packages/Amxx Pawn"
git submodule add -- https://github.com/evandrocoan/AutoFileName                       "Packages/AutoFileName"
git submodule add -- https://github.com/evandrocoan/BBCode                             "Packages/BBCode"
git submodule add -- https://github.com/evandrocoan/sublime-better-coffeescript        "Packages/Better CoffeeScript"
git submodule add -- https://github.com/evandrocoan/BufferScroll                       "Packages/BufferScroll"
git submodule add -- https://github.com/evandrocoan/ChannelRepositoryTools             "Packages/ChannelRepositoryTools"
git submodule add -- https://github.com/evandrocoan/ClearCursorsCarets                 "Packages/Clear Cursors Carets"
git submodule add -- https://github.com/evandrocoan/SublimeClipboardScopeCopy          "Packages/Clipboard Scope Copy"
git submodule add -- https://github.com/evandrocoan/ColorHighlighter                   "Packages/Color Highlighter"
git submodule add -- https://github.com/evandrocoan/ColorHelper                        "Packages/ColorHelper"
git submodule add -- https://github.com/evandrocoan/sublime-compare-side-by-side       "Packages/Compare Side-By-Side"
git submodule add -- https://github.com/evandrocoan/CopyFilepathWithLineNumbers        "Packages/Copy Filepath With Line Numbers"
git submodule add -- https://github.com/evandrocoan/CopyWithLineNumbersReloaded        "Packages/CopyWithLineNumbersReloaded"
git submodule add -- https://github.com/evandrocoan/SublimeDefaultSyntax               "Packages/Default Syntax"
git submodule add -- https://github.com/evandrocoan/SublimeDocBlockr-jsdocs            "Packages/DocBlockr"
git submodule add -- https://github.com/evandrocoan/ExportHtml                         "Packages/ExportHtml"
git submodule add -- https://github.com/evandrocoan/SublimeExtendedTabSwitcher         "Packages/ExtendedTabSwitcher"
git submodule add -- https://github.com/evandrocoan/SublimeFileDiffs                   "Packages/FileDiffs"
git submodule add -- https://github.com/evandrocoan/FileManager                        "Packages/FileManager"
git submodule add -- https://github.com/evandrocoan/SublimeFixProjectSwitchRestartBug  "Packages/Fix Project Switch Restart Bug"
git submodule add -- https://github.com/evandrocoan/SublimeFixSelectionAfterIndent     "Packages/Fix Selection After Indent"
git submodule add -- https://github.com/evandrocoan/SublimeFixedSelectionsClear        "Packages/Fixed Selections Clear"
git submodule add -- https://github.com/evandrocoan/SublimeForceRewriteSublimeSettings "Packages/Force Rewrite Sublime Settings"
git submodule add -- https://github.com/evandrocoan/FuzzyFileNav                       "Packages/FuzzyFileNav"
git submodule add -- https://github.com/evandrocoan/FuzzyFilePath                      "Packages/FuzzyFilePath"
git submodule add -- https://github.com/evandrocoan/Gist                               "Packages/Gist"
git submodule add -- https://github.com/evandrocoan/google-spell-check                 "Packages/Google Spell Check"
git submodule add -- https://github.com/evandrocoan/sublime-goto-last-edit-enhanced    "Packages/GotoLastEditEnhanced"
git submodule add -- https://github.com/evandrocoan/SublimeText-HighlightBuildErrors   "Packages/Highlight Build Errors"
git submodule add -- https://github.com/evandrocoan/Hungry-Backspace                   "Packages/Hungry Backspace"
git submodule add -- https://github.com/evandrocoan/sublime_indent_and_braces          "Packages/Indent and braces"
git submodule add -- https://github.com/evandrocoan/sublime-invert-selection           "Packages/Invert Selection"
git submodule add -- https://github.com/evandrocoan/LaTeXTools                         "Packages/LaTeXTools"
git submodule add -- https://github.com/evandrocoan/local-history                      "Packages/Local History"
git submodule add -- https://github.com/evandrocoan/SublimeTextMarkdowToBBCode         "Packages/Markdown to BB Code Converter"
git submodule add -- https://github.com/evandrocoan/MarkdownLight                      "Packages/MarkdownLight"
git submodule add -- https://github.com/evandrocoan/SublimeNotepadPlusPlusTheme        "Packages/Notepad++ Color Scheme"
git submodule add -- https://github.com/evandrocoan/SublimeOctave                      "Packages/Octave"
git submodule add -- https://github.com/evandrocoan/SublimeOpenAutoCompletion          "Packages/Open Auto Completion"
git submodule add -- https://github.com/evandrocoan/Origami                            "Packages/Origami"
git submodule add -- https://github.com/evandrocoan/SublimeUnpackedPackagesOverride    "Packages/Override Unpacked Packages"
git submodule add -- https://github.com/evandrocoan/SublimeOverwriteCommitCompletion   "Packages/Overwrite Commit Completion"
git submodule add -- https://github.com/evandrocoan/package_control                    "Packages/Package Control"
git submodule add -- https://github.com/evandrocoan/PackageDev                         "Packages/PackageDev"
git submodule add -- https://github.com/evandrocoan/PowerCursors                       "Packages/PowerCursors"
git submodule add -- https://github.com/evandrocoan/SublimePreferencesEditor           "Packages/Preferences Editor"
git submodule add -- https://github.com/evandrocoan/sublime-project-specific-syntax    "Packages/Project Specific Syntax Settings"
git submodule add -- https://github.com/evandrocoan/SublimeRichPlainText               "Packages/Rich Plain Text"
git submodule add -- https://github.com/evandrocoan/SublimeSQLKeywordUppercase         "Packages/SQL Keyword Uppercase"
git submodule add -- https://github.com/evandrocoan/SublimeSelectAllSpellingErrors     "Packages/Select All Spelling Errors"
git submodule add -- https://github.com/evandrocoan/SublimeShellScript                 "Packages/Shell Script"
git submodule add -- https://github.com/evandrocoan/sxs-settings                       "Packages/Side-by-Side Settings"
git submodule add -- https://github.com/evandrocoan/SideBarEnhancements                "Packages/SideBarEnhancements"
git submodule add -- https://github.com/evandrocoan/SublimeTextStudioChannel           "Packages/Sublime Text Studio"
git submodule add -- https://github.com/evandrocoan/SublimeCodeIntel                   "Packages/SublimeCodeIntel"
git submodule add -- https://github.com/evandrocoan/SublimeREPL                        "Packages/SublimeREPL"
git submodule add -- https://github.com/evandrocoan/SyncedSideBar                      "Packages/SyncedSideBar"
git submodule add -- https://github.com/evandrocoan/SyntaxManager                      "Packages/SyntaxManager"
git submodule add -- https://github.com/evandrocoan/Text-Pastry                        "Packages/Text Pastry"
git submodule add -- https://github.com/evandrocoan/SublimeTextToolBar                 "Packages/Toolbar"
git submodule add -- https://github.com/evandrocoan/Trimmer                            "Packages/Trimmer"
git submodule add -- https://github.com/evandrocoan/SublimeUncrustify                  "Packages/Uncrustify"
git submodule add -- https://github.com/evandrocoan/SublimeViewSettingsFreely          "Packages/View Settings Freely"
git submodule add -- https://github.com/evandrocoan/Sublime-Wrap-Plus                  "Packages/Wrap Plus"
