
# Move some packages from `Packages` to `Packages2`
cd ..
mkdir Packages2

mv Packages{,2}/"ANSIescape"
mv Packages{,2}/"Active View Jump Back"
mv Packages{,2}/"Add Folder To Project"
mv Packages{,2}/"Advanced CSV"
mv Packages{,2}/"AdvancedNewFile"
mv Packages{,2}/"AlignTab"
mv Packages{,2}/"All Autocomplete"
mv Packages{,2}/"Amxx Pawn"
mv Packages{,2}/"AutoFileName"
mv Packages{,2}/"BBCode"
mv Packages{,2}/"Better CoffeeScript"
mv Packages{,2}/"BufferScroll"
mv Packages{,2}/"Clear Cursors Carets"
mv Packages{,2}/"Clipboard Scope Copy"
mv Packages{,2}/"Color Highlighter"
mv Packages{,2}/"ColorHelper"
mv Packages{,2}/"Compare Side-By-Side"
mv Packages{,2}/"Copy Filepath With Line Numbers"
mv Packages{,2}/"CopyWithLineNumbersReloaded"
mv Packages{,2}/"Default Syntax"
mv Packages{,2}/"DocBlockr"
mv Packages{,2}/"ExportHtml"
mv Packages{,2}/"ExtendedTabSwitcher"
mv Packages{,2}/"FileDiffs"
mv Packages{,2}/"FileManager"
mv Packages{,2}/"Fix Project Switch Restart Bug"
mv Packages{,2}/"Fix Selection After Indent"
mv Packages{,2}/"Fixed Selections Clear"
mv Packages{,2}/"Force Rewrite Sublime Settings"
mv Packages{,2}/"FuzzyFileNav"
mv Packages{,2}/"FuzzyFilePath"
mv Packages{,2}/"Gist"
mv Packages{,2}/"Google Spell Check"
mv Packages{,2}/"GotoLastEditEnhanced"
mv Packages{,2}/"Highlight Build Errors"
mv Packages{,2}/"Hungry Backspace"
mv Packages{,2}/"Indent and braces"
mv Packages{,2}/"Invert Selection"
mv Packages{,2}/"LaTeXTools"
mv Packages{,2}/"Local History"
mv Packages{,2}/"Markdown to BB Code Converter"
mv Packages{,2}/"MarkdownLight"
mv Packages{,2}/"Notepad++ Color Scheme"
mv Packages{,2}/"Octave"
mv Packages{,2}/"Open Auto Completion"
mv Packages{,2}/"Origami"
mv Packages{,2}/"Override Unpacked Packages"
mv Packages{,2}/"Overwrite Commit Completion"
mv Packages{,2}/"Package Control"
mv Packages{,2}/"PackageDev"
mv Packages{,2}/"PowerCursors"
mv Packages{,2}/"Preferences Editor"
mv Packages{,2}/"Project Specific Syntax Settings"
mv Packages{,2}/"Rich Plain Text"
mv Packages{,2}/"SQL Keyword Uppercase"
mv Packages{,2}/"Select All Spelling Errors"
mv Packages{,2}/"Shell Script"
mv Packages{,2}/"Side-by-Side Settings"
mv Packages{,2}/"SideBarEnhancements"
mv Packages{,2}/"Sublime Text Studio"
mv Packages{,2}/"SublimeCodeIntel"
mv Packages{,2}/"SublimeREPL"
mv Packages{,2}/"SyncedSideBar"
mv Packages{,2}/"SyntaxManager"
mv Packages{,2}/"Text Pastry"
mv Packages{,2}/"Toolbar"
mv Packages{,2}/"Trimmer"
mv Packages{,2}/"Uncrustify"
mv Packages{,2}/"View Settings Freely"
mv Packages{,2}/"Wrap Plus"
mv Packages{,2}/"amxmodx"
