
# Move the Sublimehq packages from `Packages` to `SublimehqPackages`
# https://stackoverflow.com/questions/44680746/how-to-use-old-newname-inside-a-shell-script-variable
cd ..
mkdir SublimehqPackages

mv {,Sublimehq}"Packages/Lisp"
mv {,Sublimehq}"Packages/Lua"
mv {,Sublimehq}"Packages/Makefile"
mv {,Sublimehq}"Packages/Markdown"
mv {,Sublimehq}"Packages/Matlab"
mv {,Sublimehq}"Packages/Objective-C"
mv {,Sublimehq}"Packages/OCaml"
mv {,Sublimehq}"Packages/Pascal"
mv {,Sublimehq}"Packages/Perl"
mv {,Sublimehq}"Packages/PHP"
mv {,Sublimehq}"Packages/Python"
mv {,Sublimehq}"Packages/R"
mv {,Sublimehq}"Packages/Rails"
mv {,Sublimehq}"Packages/Regular Expressions"
mv {,Sublimehq}"Packages/RestructuredText"
mv {,Sublimehq}"Packages/Ruby"
mv {,Sublimehq}"Packages/Rust"
mv {,Sublimehq}"Packages/Scala"
mv {,Sublimehq}"Packages/ShellScript"
mv {,Sublimehq}"Packages/SQL"
mv {,Sublimehq}"Packages/TCL"
mv {,Sublimehq}"Packages/Text"
mv {,Sublimehq}"Packages/Textile"
mv {,Sublimehq}"Packages/XML"
mv {,Sublimehq}"Packages/YAML"
mv {,Sublimehq}"Packages/LICENSE"
mv {,Sublimehq}"Packages/README.md"
mv {,Sublimehq}"Packages/.git"
mv {,Sublimehq}"Packages/ActionScript"
mv {,Sublimehq}"Packages/AppleScript"
mv {,Sublimehq}"Packages/ASP"
mv {,Sublimehq}"Packages/Batch File"
mv {,Sublimehq}"Packages/C#"
mv {,Sublimehq}"Packages/C++"
mv {,Sublimehq}"Packages/Clojure"
mv {,Sublimehq}"Packages/CSS"
mv {,Sublimehq}"Packages/D"
mv {,Sublimehq}"Packages/Diff"
mv {,Sublimehq}"Packages/Erlang"
mv {,Sublimehq}"Packages/Go"
mv {,Sublimehq}"Packages/Graphviz"
mv {,Sublimehq}"Packages/Groovy"
mv {,Sublimehq}"Packages/Haskell"
mv {,Sublimehq}"Packages/HTML"
mv {,Sublimehq}"Packages/Java"
mv {,Sublimehq}"Packages/JavaScript"
mv {,Sublimehq}"Packages/LaTeX"

printf "Success\\!\n"
